### PR TITLE
PB start page content update

### PR DESCRIPTION
**Pull request by johnkane1**
Private beta start page previously updated in response to feedback from GDS senior content designer.

This version has had content re-written in response to feedback from senior stakeholders including CICA CEO and Policy and Legal Heads of department.

Screenshot below

MVP-905 Screenshot

### CODE REVIEW

**Comment by johnkane1** [comment]
Updated screenshot containing PLADS approved content for the 2 year rule exceptions.

MVP-905 Screenshot v2

**Comment by Julieallan** [comment]
@johnkane1 were we meant to substitute the 'contact the police' line with 'contact us'? I know we have it under 'other ways to apply' but it doesn't really fit there unless we change the heading and we know we shouldn't do that. Do you think it makes more sense to have it under the what you'll need bit and remove it from the 'other..'?

**Comment by johnkane1** [comment]
> @johnkane1 were we meant to substitute the 'contact the police' line with 'contact us'? I know we have it under 'other ways to apply' but it doesn't really fit there unless we change the heading and we know we shouldn't do that. Do you think it makes more sense to have it under the what you'll need bit and remove it from the 'other..'?

Hi Julie - as discussed we already have "contact us" content on the page, albeit a bit lower down.  Have shared the screenshot with PLADS for their comments.

**Comment by johnkane1** [comment]
changed "crime" to "assault" in first line as per PLADS request.

**Comment by johnkane1** [comment]
Feedback from head of PLADS as follows
_Hi John

The opening line has changed to refer to ‘a sexual crime or abuse’ instead of ‘a sexual assault or abuse’. I don’t remember this being discussed but it’s possible I missed it. Either way, I think this needs to change back to ‘sexual assault or abuse’ to reflect the Scheme and because both ‘sexual assault’ and ‘sexual abuse’ are crimes.

The other changes we agreed have been taken into account as far as I can see.

Thanks

laura_

**Comment by Julieallan** [comment]
Looks fine to me John, thanks

**Pull request merged**
