### PR TITLE
MVP-266 Compensation screen error state content

### PR DESCRIPTION
**Pull request by johnkane1**
Error content created as per BDDs.  Screenshot below for when a user does not select a radio button.

mvp-266 other comp - no radios selected

### CODE REVIEW

**Comment by johnkane1** [comment]
4 further error states created.  Screenshots below

mvp-266 other comp - yes selected but no source entered
mvp-266 other comp - yes selected but no amount entered
mvp-266 other comp - yes but waiting selected but no source entered
mvp-266 other comp - no selected no text entered

**Comment by Julieallan** [comment]
These all look fine @johnkane1

**Comment by johnkane1** [comment]
@Julieallan given recent conversation with @sinclairs about field IDs I think we should park this until we make a decision on the redesign of the other comp flow.

**Comment by Julieallan** [comment]
Agreed @johnkane1

**Comment by johnkane1** [comment]
After discussion with @Julieallan @maxinedivers  and @sinclairs  decision made to:
1) Retain conditionally revealing field for "no"
2) remove the conditionally revealing fields for "yes" and "yes. but I am still waiting"
3) create a new page that is triggered by either of the "yes" answers and which collects the source and amount of other comp

**Comment by johnkane1** [comment]
Error states revised.  Screenshots below for when user:

- doesnt select a radio button on "Have you applied for other comp"
- doesnt provide an explanation for answering no
- doesnt enter a source of compensation on the "other compensation" screen
- doesnt enter an amount of compensation on the "other compensation" screen

mvp-266 other comp - no radios selected
mvp-266 other comp - no selected no text entered
mvp-266 other comp - no source entered
mvp-266 other comp - no amount entered

**Comment by johnkane1** [comment]
Redesigned screenshots below

mvp-266 other compensation source and amount

**Comment by johnkane1** [comment]
content changes on other compensation screen screenshots below

mvp-266 other comp - no source entered
mvp-266 other comp - no amount entered
mvp-266 other compensation source and amount

**Comment by Julieallan** [comment]
@johnkane1  re content, it matches what we tested in our last UR so happy with that

**Pull request merged**
