### PR TITLE
MVP-507 Page not found - 404 error - created

### PR DESCRIPTION
**Pull request by johnkane1**
Page not found/404 error page created in accordance with GDS design system pattern https://design-system.service.gov.uk/patterns/page-not-found-pages/

Screenshot below

mvp-507 page not found 404 error

### CODE REVIEW

**Comment by johnkane1** [comment]
Internal server error / 500 error page created in accordance with GDS design system pattern https://design-system.service.gov.uk/patterns/problem-with-the-service-pages/

Screenshot below
mvp-507 internal server error 500 error

**Comment by Julieallan** [comment]
@johnkane1 the 500 error says 'We have not saved your answers' in terms of them being able to come back to them but we may have stored them for a bit, server side. Could this mislead them?

**Comment by Julieallan** [comment]
@johnkane1 I've also raised separate tickets for @maxinedivers to review the design and patterns. This will likely be in the next sprint. Can we not merge until after review? Thanks.

**Comment by johnkane1** [comment]
I discussed this with @sinclairs  last week and it was agreed the current content is sufficient.  Will merge the branch for now and we can revisit if there are any issues arising.

**Pull request merged**
