### PR TITLE
MVP 681 police force

### PR DESCRIPTION
**Pull request by maxinedivers**
New concept "as is" is now added to the concept section. It asks the police force with a select menu option containing all forces across the UK. 

Also added a the help reveal below it - not sure if we are able to mention calling the police 101 in there?

This design pattern is from GDS https://design-system.service.gov.uk/components/select/
This is the only one they have and is used for sorting tables and data.  I have made the first option blank and disabled it using code so that the first option is blank and not accepted if the user just selects continue to ensure this works for us. Bit clunky.

Ideally would like the dropdown example from: https://alphagov.github.io/accessible-autocomplete/examples/  to be used. the one where when they click on the pattern the full list is shown but they are able to type to search too. 

Also may need to confirm the final list of police forces. The list I have used is taken from the justice portal but would like it confirmed to ensure it contains an accurate up-to-date list.

### CODE REVIEW

**Comment by Julieallan** [comment]
This looks good @maxinedivers. Some of the Scottish ones on Justice are still displaying as the old names so Alan has given me the correct list and I've shared them with you via google sheets.

**Comment by johnkane1** [comment]
@Julieallan  I am not sure we should have any hint text here at the moment.   We could add some if the private beta research identifies a need.  Otherwise the content is fine (with the exception of the drop down contents which we have already discussed)

**Comment by Julieallan** [comment]
Agreed we can leave police force list as is on the prototype. Dev has the correct list of forces which they will use when developing any dropdown.

**Comment by Julieallan** [comment]
Also I agree we should leave out any hint text until we test with users.

**Comment by johnkane1** [comment]
@Julieallan I have made content changes, removing the hint text and aligning the reveal content with the page heading.

**Pull request merged**
