### PR TITLE
MVP-518 Application delay

### PR DESCRIPTION
**Pull request by johnkane1**
Design of page changed in response to EMB and User feedback.

- Checkboxes with conditionally reveal fields used
- Police advise and court advice options merged into one "advised to wait"
- heading changed to make it less similar to the other delay question

Screenshot below
image

### CODE REVIEW

**Comment by gavinwye** [comment]
I don't think we need to say "briefly" as there is only one line for people to fill out. Each of the text inputs should be the same width as the second option.

**Comment by gavinwye** [comment]
Also, I think we need to find a different way to say 'delay' to a user they will have done this as soon as they could and in their eyes, it won't be a delay.

**Comment by Julieallan** [comment]
I don't think we should use 'choose'. For all other options pages we use 'select' so we should be consistent. Also, if we stick with 'reasons' it reduces the need for further words like 'option' and 'explain'.

**Comment by johnkane1** [comment]
> I don't think we should use 'choose'. For all other options pages we use 'select' so we should be consistent. Also, if we stick with 'reasons' it reduces the need for further words like 'option' and 'explain'.

Agree we could change Choose to select if we are going to separate the two "Delay" questions. otherwise there is a danger they will still look similar.  As for the fields using verbs helps the user complete the fields appropriately so I would rather stick with them.

**Comment by Julieallan** [comment]
Thanks @johnkane1, helpful hints good, testing will tell if we need a box under every reason, if someone selects all it looks a bit daunting.

**Pull request merged**
