### PR TITLE
MVP-538 OCJ Content changes

### PR DESCRIPTION
**Pull request by johnkane1**
Content changes made in response to UR feedback.  Not yet ready to be merged as code needs tidied up for reveal text

### CODE REVIEW

**Comment by johnkane1** [comment]
Consulted with content colleagues on the gov.uk slack channel re the use of colons or dashes in radio button labels.  Advice was that colons should be used viz https://www.gov.uk/guidance/content-design/content-types#titles

_Titles
What’s the story? Tell the story in a few words:

headlines: aim for 65 characters max
use a colon not a dash to separate: Google does not recognise dashes_

**Comment by johnkane1** [comment]
Content changes made as follows:
- more specific about not needing medicals for short journey
- clarification that DMI referral may be made if user doesn't already have a diagnosis
- Options prefix added to sub headings and radio labels

Also further email discussion with PLADS around DMI  reveal content.  Screenshots of research sent to them below
current dmi content
plads proposed dmi content
jk proposed dmi content
readability reseearch for dmi description

**Comment by Julieallan** [comment]
@johnkane1, we can wait on PLADs feedback - in the 3rd option, which is simpler, I'm not sure 'large' conveys the same message as 'substantial'. Also, 'you doing' doesn't read as well but it's down to the user!

**Comment by Julieallan** [comment]
@johnkane1, happy for you to merge it now so we can test today with new user.

**Pull request merged**
