### PR TITLE
MVP-540 Police force content

### PR DESCRIPTION
**Pull request by johnkane1**
Users are having problems identifying the correct force from the autocomplete tool.  This change removes the autocomplete function if the user says the incident happened in either Scotland or Wales and instead displays a complete list of forces for that country using radio buttons.  Various sources online state that cut off point between radio buttons and a drop down is 7.  Asked content community on Slack and got the answer 5, and that we should be asking the user questions to get to a point where we only have to show that many.  I think this is something that could be achieved when we have an api lookup linked to the town/city answer in the location screen, but for now it would be worth testing whether the 14 radio buttons for Scotland is more or less helpful than  the autocomplete.  Short demo attached below
mvp-540 police force

### CODE REVIEW

**Comment by Julieallan** [comment]
I think it's more helpful but very long. The Welsh forces do not look as bad. Have you removed the other forces - Civil Nuclear? We'll need to double check them off the tariff list. I'll ask Alan for that as the one he gave me earlier was not up-to-date.

**Comment by johnkane1** [comment]
Content redesigned to explore solving the autocomplete failure using a series of pages with radio buttons, which maps English forces to their particular administrative region, or in the case of the Met a London borough.  The ambition was to get a maximum of between 5 and 7 radios per page, so some of the geographical groupings are currently arbitrary to achieve that.  Demo below of prototype which accommodates a scenario where the crime was reported to one of 4 Met borough commands in West/Central London.
mvp-540 english police force demo

**Comment by Julieallan** [comment]
We need to test the autocomplete with users injured in England as it may be completely different for them. Police Scotland is unique in how it's made up. I would say we leave it as is for English forces and see how it works.

**Comment by johnkane1** [comment]
@Julieallan  I have reverted the design to autocomplete for England/Somewhere else and Radios for Scotland/Wales.
I have also refined the police force content in autocomplete to:
- remove Civil Nuclear Defence
- make Scottish forces display as "Police Scotland Greater Glasgow", removing "service of" and the brackets around the division name.

**Comment by Julieallan** [comment]
Thanks @johnkane1, it may be that we will adopt the design you suggested but let's see what feedback we get on the autofill first.

**Comment by Julieallan** [comment]
'@johnkane1, we will need to split the Met down to divisions as it affects the routing of cases to the correct Ops teams.

**Comment by johnkane1** [comment]
> '@johnkane1, we will need to split the Met down to divisions as it affects the routing of cases to the correct Ops teams.

No problem @Julieallan  I will get it done today

**Comment by gavinwye** [comment]
@johnkane1 have you put British transport police at the bottom of the list because it's the least selected option? Do we have data to back this up?

**Pull request merged**
