### PR TITLE
Mvp 773 - Footer links and content

### PR DESCRIPTION
**Pull request by johnkane1**
Content created for Cookies and Contact page. Screenshots below

MVP-773 Cookies
MVP-773 Contact us

### CODE REVIEW

**Comment by Julieallan** [comment]
@johnkane1 under 'Post' should we include the name of the organisation as it's not shown on the page anywhere else?

**Comment by Julieallan** [comment]
@sinclairs re Cookies specific to our service - Adrian provided these last year for John. Do you know if they are still relevant or if we need to add anything else? Thanks

**Comment by maxinedivers** [comment]
Looks great! Theres a close button on the contact but not cookies? What does that button do? Don't think we need it -  do all the new links open in a new tab? I think thats the pattern from what I've seen in other services

**Comment by johnkane1** [comment]
> Looks great! Theres a close button on the contact but not cookies? What does that button do? Don't think we need it - do all the new links open in a new tab? I think thats the pattern from what I've seen in other services

Close was copied from the other service I looked at (passport office), can simply remove it though.  I can change the hrefs for the links to do that too.

**Comment by johnkane1** [comment]
Pushed following changes

* added missing third bullet on cookies page
* links now open in new tabs
* removed close button
* updated first line of post address

**Comment by johnkane1** [comment]
MVP-773 Cookies

**Comment by johnkane1** [comment]
MVP-773 Contact us

**Comment by Julieallan** [comment]
Thanks @johnkane1

**Pull request merged**
