### PR TITLE
MVP-794 content changes

### PR DESCRIPTION
**Pull request by johnkane1**
Changes made as follows
Overview page

- Removed inset text for NI service

- Called out the costs nothing/dont need legal reps content

Make a claim

- updated same roof content and CTA
- updated the victim support content

Start SRR

- New title
- changed call out for those not affected to a warning pattern
- provided a list of things user will need to give us in other ways to make enquiry

CYA
changes made to Submit content

### CODE REVIEW

**Comment by maxinedivers** [comment]
Love the new title on the start page - really tells the user where they are should they land on this page and what they are doing. 

In the bullet point "a phone number we contact you on" - I think you've missed a word?

In the bullet point: assess your application against the requirements of the current Criminal Injuries Compensation Scheme -  should we make the scheme part a link maybe? Not sure....

On the preferred days I've put "which days would be best.." and on the times Ive put "which times are best" should we maybe make both the same? So "Which days are best for us to call you?" and "Which times of the day are best for us to call you?"??

On the submit page - If we aren't putting a reveal under the button - I would move it back up and take out the 'more' word - what you guys think?

The GDS design pattern for buttons says
"Write button text in sentence case, describing the action it performs. For example:
‘Start now’ at the start of the serviceShould the submit button say Submit enquiry?"
So I think we should we make the button on the start page say "Start now" and the submit page say "Submit enquiry"

Looking great :)

**Comment by johnkane1** [comment]
@maxinedivers have implemented most of the suggested changes you mentioned.  Wondering about the link tot he scheme though as it is a PDF rather than a web page.

**Comment by Julieallan** [comment]
@johnkane1 I know we'll be looking at the content in more details with PLADS, but on the start page, its not just about living with the offender during that period but about the injury being sustained then too. 

Under other ways to apply, do we need to list out what they need? We've told them the main things above. Everything else they would know. 

I would leave out the Scheme unless the business pushes back, it's a big document that most people don't read or they get stuck in it.

Should green buttons match - start enquiry/submit your enquiry - leave out 'your'? 

It's coming along nicely!

**Comment by maxinedivers** [comment]
thanks John

Yeah leave the 'your' out I think too Julie!

**Comment by johnkane1** [comment]
@Julieallan 
I have updated the introductory content re SRR on both the Make a claim and Start pages.

I do think we need to list out the things users require for other ways to apply as we do not specifically say anywhere else (apart from in the actual enquiry) what they will need.

I wont link to the scheme.  Do you mean remove any mention of it at all?

**Comment by Julieallan** [comment]
Thanks @johnkane1 

In terms of listing out what they'll need, we don't list them all in the online enquiry part, we only tell them the things they may have to find. Would this not be enough? Or if it's needed should we have it at the top?

I think it's fine to mention the Scheme without adding a link to it

**Comment by johnkane1** [comment]
@Julieallan  @maxinedivers 
as discussed the list of required information has been moved into the postal enquiry section.

**Comment by johnkane1** [comment]
I have changed any references to "Enquiry" to "Call-back" as that seems to be the preferred nomenclature for the service.  I will update content further when business responds to this weeks workshop outputs.

**Comment by johnkane1** [comment]
additional bullet points added to before you start section on SRR start page to accommodate workshop recommendations as follows:
•	Explanation around the destruction of paper and electronic records to set expectations for the user. 
•	Advise the applicant the call back will be from an unknown number.

**Comment by Julieallan** [comment]
These changes look good @johnkane1

**Comment by johnkane1** [comment]
@maxinedivers @Julieallan 
I have updated the branch with the content changes requested by PLADS (See attached document).
There are a few things on the list that are questions for the business so I will share this with Nicola Watson to pass on.  Please review the deployment and let me know if you think I have addressed everything.
[SRR notes PLADS review 170419.docx](https://github.com/CriminalInjuriesCompensationAuthority/apply-for-compensation-prototype/files/3093333/SRR.notes.PLADS.review.170419.docx)

**Comment by Julieallan** [comment]
@johnkane1 it's looking good. Two points:

Make a claim page: 'Until 21 May 2021..' sounds as though this is a strict deadline and they can't apply after that date - at the moment they can still apply but it will be subject to over 2 years rules. I did speak to Pat to make sure this was the case and she said it may change anyway so we don't need to get hung up on it 
Start page: It mentions taking out the bullet point about previous application no. It's still on the bit about 'post'. Is that ok? I think it makes sense to have it but just wanted to make sure it wasn't discussed.

Thanks

**Comment by johnkane1** [comment]
Hi Julie
the removal of prev app no from postal apps wasnt raised as an issue.  Yes the date may change and we are still waiting for answers from the business on other things such as response times and call durations.  If you and @maxinedivers  are happy I will merge this into prototype and update PLADS

**Comment by Julieallan** [comment]
thanks @johnkane1 I'm happy with that

**Pull request merged**
